import type { LoveAdviceRule } from "./types";

export const LOVE_ADVICE_RULES = [
  {
    ruleId: "C-SP-001",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 1권 L480-L555; 정복하는 남자 1권 L1359-L1369",
    sourceExcerpt: "상대에게 근거 없는 기대와 환상을 덮어씌우면 기대에서 벗어나는 순간 실망과 집착이 생긴다. 강한 끌림은 억압된 욕구의 투사일 수 있다.",
    triggerPattern: "짧은 인상, 별자리 해석, 첫 대화만으로 상대를 크게 이상화함",
    riskExpression: "상대의 실제 행동을 보기 전에 감정이 앞서고, 기대와 다른 신호가 보이면 급격히 실망하거나 매달림",
    adviceDirection: "끌림·상상·행동 근거를 분리해서 관찰하게 한다. 감정이 커질수록 검증 기간을 늘린다.",
    actionExample: "관심 상대에 대해 `느낌`, `확인된 행동`, `아직 모르는 것`을 3칸으로 적고 2주 이상 행동 근거를 모은다.",
    forbiddenFrame: "“사람 보는 눈이 없다”, “남자는/여자는 원래 그렇다”",
    notes: "C 구조의 핵심 rule. 자미두수 해석 결과의 `과대해석`, `환상화`, `도화 과몰입` 리스크 후처리에 연결.",
    matchTags: ["projection", "fantasy_idealization", "confirmation_seeking", "pace_control"],
    priority: 11
  },
  {
    ruleId: "C-SP-002",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 2, 6],
    sourceBook: "소유하는 여자 2권 L202-L265, L314-L337",
    sourceExcerpt: "상상 속 이상형이나 드라마 같은 만남만 진짜 사랑이라고 보면 실제 관계·소개팅·평범한 일상성을 거부하게 된다.",
    triggerPattern: "자연스러운 운명적 만남만 기다리고 소개팅·주선·반복 만남을 낮게 봄",
    riskExpression: "실제 사람보다 상상 속 서사를 사랑하고, 현실 접점이 생겨도 환상이 깨지는 순간 후퇴함",
    adviceDirection: "운명감이 없어도 관계는 반복 접촉과 일상성으로 만들어진다고 번역한다.",
    actionExample: "한 달에 2회 이상 소개/모임/취미 접점을 만들고, 첫 만남의 설렘보다 두 번째 만남의 편안함을 기록한다.",
    forbiddenFrame: "“운명적 상대만 기다려라”, “드라마 같은 사랑이 진짜다”",
    notes: "섹션 4의 인연 유입 행동과도 연결하되, 중심축은 솔로 패턴 교정.",
    matchTags: ["projection", "fantasy_idealization", "encounter_action", "approach_avoidance"],
    priority: 12
  },
  {
    ruleId: "C-SP-003",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 2권 L389-L513",
    sourceExcerpt: "상대가 잘해준 99번보다 부족한 1번에 집중하면 충분히 괜찮은 관계도 불만과 의심으로 무너질 수 있다.",
    triggerPattern: "한 번의 연락 지연·표현 부족을 애정 감소의 증거로 확대함",
    riskExpression: "확인 요구, 서운함 폭주, 상대의 피로 누적, 괜찮은 관계의 조기 파괴",
    adviceDirection: "부족한 점을 보되 전체 행동 패턴과 비율을 함께 보게 한다. 기준은 줄이고 핵심만 남긴다.",
    actionExample: "서운한 일이 생기면 `최근 10개의 행동 근거` 중 반복인지 단발인지 먼저 체크한다.",
    forbiddenFrame: "“99번 잘해도 1번 못하면 끝”, “사랑하면 항상 알아서 맞춰야 한다”",
    notes: "여성 편향으로 쓰지 말고 성별 중립의 확인 욕구/결점 찾기 패턴으로 사용.",
    matchTags: ["confirmation_seeking", "contact_anxiety", "words_over_actions", "conflict_expression"],
    priority: 13
  },
  {
    ruleId: "C-SP-004",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 1권 L644-L703; 정복하는 남자 4권 L363-L399",
    sourceExcerpt: "현재 감정은 강하게 느껴지고 미래 감정은 흐릿하게 느껴진다. 감정 최고점에서 판단하면 사후합리화가 붙는다.",
    triggerPattern: "불안·설렘·질투가 올라오자마자 고백, 추궁, 차단, 재회 연락을 함",
    riskExpression: "후회할 말과 결정, 관계 속도 붕괴, 반복적인 감정 과속",
    adviceDirection: "감정은 인정하되 판단과 행동은 시간차를 두게 한다.",
    actionExample: "중요 메시지는 10분·10개월·10년 뒤 후회 여부를 적고, 불안 최고점에서는 24시간 예약 발송만 허용한다.",
    forbiddenFrame: "“느낌이 곧 답이다”, “감정대로 밀어붙여라”",
    notes: "실행 준비와도 강하게 연결됨.",
    matchTags: ["pace_control", "contact_anxiety", "confirmation_seeking", "post_breakup_idealization"],
    priority: 14
  },
  {
    ruleId: "C-SP-005",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 1권 L132-L136; 정복하는 남자 3권 L346-L361; 정복하는 남자 4권 L87-L89",
    sourceExcerpt: "연애를 삶의 목적 전체로 만들면 상대에게 과부하가 걸리고 자기 세계가 사라진다.",
    triggerPattern: "관심이 생기면 일, 친구, 루틴보다 상대 반응을 1순위로 둠",
    riskExpression: "매달림, 자기상실, 상대 압박, 관계 밖 매력 저하",
    adviceDirection: "관계 밖의 자기 역할과 리듬을 유지하는 것이 관계 안정의 기반이라고 안내한다.",
    actionExample: "주 3개 고정 루틴(운동/작업/친구)을 먼저 캘린더에 넣고, 데이트는 그 위에 배치한다.",
    forbiddenFrame: "“연애가 인생의 전부다”, “상대를 붙잡기 위해 모든 걸 맞춰라”",
    notes: "섹션 6 준비 루틴의 기본 rule.",
    matchTags: ["overcentering_love", "self_routine", "charm_operation"],
    priority: 15
  },
  {
    ruleId: "C-SP-006",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 4권 L1000-L1032; 정복하는 남자 2권 L530-L562",
    sourceExcerpt: "건전한 관계에는 개인적인 공간과 시간이 필요하다. 친밀함이 강할수록 분리성 과제가 생긴다.",
    triggerPattern: "친밀해질수록 매일 함께해야 안심하고, 혼자 있는 시간을 거절로 해석함",
    riskExpression: "상대의 회복·작업 리듬 침범, 답답함, 회피 반응 유발",
    adviceDirection: "거리 두기를 애정 부족이 아니라 관계의 산소로 설명한다.",
    actionExample: "연락·만남이 줄었을 때 바로 묻기 전에 `상대 일정/내 불안/필요한 요청`을 분리해 적는다.",
    forbiddenFrame: "“항상 붙어 있어야 사랑이다”, “연락 안 하면 마음이 식은 것”",
    notes: "성별화하지 않고 애착/분리성 패턴으로 사용.",
    matchTags: ["boundary_failure", "contact_anxiety", "confirmation_seeking", "approach_avoidance"],
    priority: 16
  },
  {
    ruleId: "C-SP-007",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 4권 L1149-L1206; 정복하는 남자 4권 L320-L345",
    sourceExcerpt: "스마트폰 연락은 관계를 깊게 하는 실제 만남을 대체하지 못하고, 예측 가능한 반복 연락은 피로와 집착을 만든다.",
    triggerPattern: "연락 빈도를 애정 척도로 삼고, 답장 지연을 관계 위기로 해석함",
    riskExpression: "감시·확인 루프, 대화 소재 고갈, 실제 만남의 밀도 하락",
    adviceDirection: "연락의 양보다 실제 만남과 대화의 질을 우선하게 한다.",
    actionExample: "매일 안부 템플릿을 줄이고, 다음 만남에서 나눌 주제 1개와 실제 제안 1개만 남긴다.",
    forbiddenFrame: "“연락 빈도 = 사랑의 크기”, “답장으로 상대를 조절하라”",
    notes: "카톡/SNS 원문은 조작 프레임이 많으므로 제품에서는 연락 위생 rule로만 사용.",
    matchTags: ["confirmation_seeking", "contact_anxiety", "conflict_expression", "encounter_action"],
    priority: 17
  },
  {
    ruleId: "C-SP-008",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 2, 6],
    sourceBook: "소유하는 여자 4권 L1282-L1295; 정복하는 남자 4권 L62-L66",
    sourceExcerpt: "외로움을 잊기 위한 만남은 평소 좋아하지 않거나 맞지 않는 사람에게도 쉽게 끌리게 만든다.",
    triggerPattern: "이별 직후, 혼자 있는 공허함, 주변 비교 때문에 급하게 사람을 찾음",
    riskExpression: "적합하지 않은 관계 진입, 반복 이별, 외로움의 외주화",
    adviceDirection: "외로움 해소와 호감 판단을 분리하게 한다.",
    actionExample: "새 만남 전 `외로움 점수`가 7 이상이면 약속을 잡기 전에 운동·친구·수면 루틴을 먼저 실행한다.",
    forbiddenFrame: "“사랑은 새 사랑으로만 잊는다”, “혼자인 상태는 실패다”",
    notes: "싱글 타겟 리포트에 직접 유용.",
    matchTags: ["overcentering_love", "self_routine", "boundary_failure", "loneliness_based_choice"],
    priority: 18
  },
  {
    ruleId: "C-SP-009",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 4권 L1210-L1241, L1262-L1281",
    sourceExcerpt: "이별 후 상대 이상화와 자기연민은 슬픔에 중독되게 한다. 이별기는 고독력과 생활 습관을 재정비하는 시기로 쓸 수 있다.",
    triggerPattern: "끝난 관계를 미완성 드라마처럼 붙잡고 재회 상상에 몰입함",
    riskExpression: "재회 집착, 생활 붕괴, 다음 관계 준비 지연",
    adviceDirection: "감정 회복을 기다리되 생활 루틴을 먼저 복구하게 한다.",
    actionExample: "30일 동안 수면·식사·운동·음주 중 하나를 회복 지표로 정하고, 전 연인 탐색 행동을 차단한다.",
    forbiddenFrame: "“재회만이 회복이다”, “상대를 되찾아야 내가 괜찮아진다”",
    notes: "현재 솔로 상태의 원인이 이별 후유증일 때 사용.",
    matchTags: ["fantasy_idealization", "encounter_action", "pace_control", "overcentering_love"],
    priority: 19
  },
  {
    ruleId: "C-SP-010",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 4, 6],
    sourceBook: "정복하는 남자 4권 L351-L403",
    sourceExcerpt: "거절 두려움 같은 단기 감정은 시간이 지나면 희미해진다. 하지 않은 후회가 더 오래 남을 수 있다.",
    triggerPattern: "마음에 드는 사람이 있어도 거절·쪽팔림 때문에 접근하지 못함",
    riskExpression: "기회 회피, 자기효능감 하락, 머릿속 시뮬레이션만 반복",
    adviceDirection: "감정의 위험과 실제 손실을 구분하게 한다.",
    actionExample: "10-10-10 질문 후 10개월 뒤 손실이 작다면 5초 안에 가벼운 인사부터 실행한다.",
    forbiddenFrame: "“두려움이 없어질 때까지 기다려라”, “완벽한 멘트를 준비하라”",
    notes: "인연 유입 행동과 실행 준비 사이의 연결 rule.",
    matchTags: ["pace_control", "overcentering_love", "self_routine", "approach_avoidance"],
    priority: 20
  },
  {
    ruleId: "C-SP-011",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 3권 L560-L570; 정복하는 남자 2권 L724-L739",
    sourceExcerpt: "말보다 실제 행동과 계획이 관계 신뢰를 만든다. 달콤한 말이나 막연한 확신은 근거가 되기 어렵다.",
    triggerPattern: "말로 받은 약속, 분위기, 가능성만 믿고 관계를 판단함",
    riskExpression: "기대만 키우고 행동 없는 사람에게 오래 묶임",
    adviceDirection: "상대의 말보다 반복 행동·시간 사용·계획 실행을 보게 한다.",
    actionExample: "상대의 약속은 `말`, `구체 계획`, `실행 여부`로 나누어 3회 이상 반복성을 본다.",
    forbiddenFrame: "“말이 달콤하면 진심이다”, “상대가 언젠가 바뀔 것이다”",
    notes: "끌림-적합 판별과 중복 가능하나 대표축은 솔로 패턴 교정.",
    matchTags: ["words_over_actions", "charm_operation"],
    priority: 21
  },
  {
    ruleId: "C-SP-012",
    axisMain: true,
    axisName: "솔로 패턴 교정",
    obitSections: [1, 6],
    sourceBook: "소유하는 여자 4권 L1033-L1053",
    sourceExcerpt: "공개적 조롱·험담은 친밀한 장난이 아니라 관계의 안전감과 존중을 깎는 행동이다.",
    triggerPattern: "친하다는 이유로 상대를 사람들 앞에서 낮추거나 불만을 제3자에게 흘림",
    riskExpression: "수치심, 방어성, 장기 신뢰 손상",
    adviceDirection: "갈등은 관계 내부에서 다루고, 유머와 비하를 구분하게 한다.",
    actionExample: "상대가 없는 자리에서 불만을 말하기 전 `당사자에게 요청 가능한 문장`으로 바꿔 적는다.",
    forbiddenFrame: "“망신을 줘야 고친다”, “상대를 깎아야 주도권이 생긴다”",
    notes: "장기 관계 조언이지만 싱글의 관계 준비에도 중요.",
    matchTags: ["words_over_actions", "conflict_expression"],
    priority: 22
  },
  {
    ruleId: "C-JD-001",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2, 6],
    sourceBook: "소유하는 여자 2권 L498-L513",
    sourceExcerpt: "솔로 기간이 길어질수록 습관성 결점 찾기가 강해질 수 있다. 기준은 낮추는 것이 아니라 단순화해야 한다.",
    triggerPattern: "조건표가 길고, 작은 단점 하나로 후보를 계속 탈락시킴",
    riskExpression: "현실 접점 축소, 충분히 괜찮은 사람을 놓침",
    adviceDirection: "절대 불가 조건 1~2개와 선호 조건 1~2개로 압축하게 한다.",
    actionExample: "`절대 안 되는 것 2개`, `있으면 좋은 것 2개`, `협의 가능한 것`을 분리한다.",
    forbiddenFrame: "“눈을 낮춰라”, “아무나 만나라”",
    notes: "섹션 2의 기준 설정 핵심 rule.",
    matchTags: ["boundary_failure", "ideal_type_confusion", "condition_overload", "encounter_action"],
    priority: 21
  },
  {
    ruleId: "C-JD-002",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2],
    sourceBook: "소유하는 여자 2권 L519-L550",
    sourceExcerpt: "나이·키·연봉·자산 같은 특정 형태만 좇으면 이상형이 아니라 우상형이 된다.",
    triggerPattern: "상대의 삶의 방향보다 조건·이미지·스펙 형태에 집중함",
    riskExpression: "실제 관계 운영 가치와 무관한 조건에 끌림",
    adviceDirection: "형태 조건 뒤에 있는 가치와 생활 방향을 찾아내게 한다.",
    actionExample: "조건 하나마다 `이 조건으로 내가 얻고 싶은 관계 감각은 무엇인가`를 적는다.",
    forbiddenFrame: "“스펙이 맞으면 좋은 상대다”, “조건표가 곧 이상형이다”",
    notes: "Obit에서는 별 해석 후 `실제로 잘 맞는 사람` 설명에 사용.",
    matchTags: ["ideal_type_confusion", "condition_overload", "charm_operation"],
    priority: 22
  },
  {
    ruleId: "C-JD-003",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2],
    sourceBook: "정복하는 남자 1권 L1202-L1233",
    sourceExcerpt: "의식적으로 말하는 이상형과 실제로 끌리는 대상은 다를 수 있다. 건강한 조건과 본능적 끌림은 구분해야 한다.",
    triggerPattern: "편안하고 안정적인 사람을 원한다고 말하지만 반복적으로 불안정한 사람에게 흔들림",
    riskExpression: "자기 기준을 오해하고 같은 유형 반복",
    adviceDirection: "좋아한다고 말하는 조건과 실제 행동으로 선택한 유형을 비교하게 한다.",
    actionExample: "최근 끌렸던 사람 3명의 공통점과 오래 편했던 사람 3명의 공통점을 따로 쓴다.",
    forbiddenFrame: "“말한 이상형이 진짜 욕구다”, “끌리면 무조건 맞는 사람이다”",
    notes: "연애 실패 반복 원인 설명에 적합.",
    matchTags: ["overcentering_love", "self_routine", "words_over_actions", "ideal_type_confusion"],
    priority: 23
  },
  {
    ruleId: "C-JD-004",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2],
    sourceBook: "소유하는 여자 1권 L617-L620; 정복하는 남자 4권 L637-L685",
    sourceExcerpt: "안정감만으로 끌림이 생기지 않을 수 있고, 예측 불가능성만으로 적합성이 보장되지도 않는다.",
    triggerPattern: "편안한 사람은 심심하고, 긴장되는 사람은 특별하다고 느낌",
    riskExpression: "불안을 사랑으로 착각하거나, 안정형을 초반 재미 없음으로 탈락시킴",
    adviceDirection: "긴장감과 신뢰성을 별도 지표로 판별하게 한다.",
    actionExample: "상대를 `설렘`, `안심`, `존중`, `일관성` 4점 척도로 평가한다.",
    forbiddenFrame: "“불안해야 사랑이다”, “편하면 매력이 없는 것이다”",
    notes: "C 구조의 끌림-적합 핵심 rule.",
    matchTags: ["public_contempt", "charm_operation"],
    priority: 24
  },
  {
    ruleId: "C-JD-005",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2, 6],
    sourceBook: "소유하는 여자 3권 L560-L570; 정복하는 남자 2권 L601-L619",
    sourceExcerpt: "좋은 말보다 작은 기대를 만들고 실제로 증명하는 반복이 신뢰를 만든다.",
    triggerPattern: "표현이 크거나 말이 능숙한 사람에게 쉽게 확신을 줌",
    riskExpression: "행동 없는 말에 오래 묶이고, 실제 안정성 판별이 늦어짐",
    adviceDirection: "상대가 기대를 만든 뒤 어떻게 증명하는지 보게 한다.",
    actionExample: "약속·계획·사과·배려가 실제 행동으로 이어졌는지 날짜별로 체크한다.",
    forbiddenFrame: "“말을 잘하면 진심이다”, “큰 선언이 곧 책임감이다”",
    notes: "C-SP-011과 연결하되 판별 기준으로 사용.",
    matchTags: ["words_over_actions", "conflict_expression", "charm_operation"],
    priority: 25
  },
  {
    ruleId: "C-JD-006",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2],
    sourceBook: "정복하는 남자 3권 L1498-L1524",
    sourceExcerpt: "친밀한 주변 사람은 가치관과 생활 방식을 반영할 수 있다. 다만 감시·유도심문이 아니라 관찰 근거로만 사용한다.",
    triggerPattern: "상대의 말만 보고 생활권·친구·평판 신호를 보지 않음",
    riskExpression: "장기 관계에서 생활 가치 충돌을 뒤늦게 발견",
    adviceDirection: "상대의 가까운 관계망을 가치관 힌트로만 참고하게 한다.",
    actionExample: "상대가 자주 만나는 사람들과 대화 주제, 시간 사용 방식, 갈등 처리 방식을 관찰한다.",
    forbiddenFrame: "“친구를 몰래 캐라”, “주변 사람으로 상대를 단정하라”",
    notes: "원문 유도심문·감시 표현은 제거.",
    matchTags: ["words_over_actions", "conflict_expression", "charm_operation"],
    priority: 26
  },
  {
    ruleId: "C-JD-007",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2],
    sourceBook: "정복하는 남자 3권 L1527-L1534",
    sourceExcerpt: "연애는 원하는 요소만 고르는 뷔페가 아니라 장점과 부족한 점을 함께 받아들이는 선택에 가깝다.",
    triggerPattern: "완벽한 사람을 찾거나, 하나의 단점만으로 전체를 폐기함",
    riskExpression: "관계 진입 지연, 만성 비교, 선택 후 책임 회피",
    adviceDirection: "치명적 위험과 조율 가능한 부족함을 구분하게 한다.",
    actionExample: "단점을 `안전/존중 침해`, `생활 조율 필요`, `취향 차이`로 분류한다.",
    forbiddenFrame: "“완벽한 사람을 찾아라”, “부족함이 있으면 모두 탈락”",
    notes: "제품 문체에 적합한 비서열화 판별 rule.",
    matchTags: ["approach_avoidance", "public_contempt", "charm_operation"],
    priority: 27
  },
  {
    ruleId: "C-JD-008",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2, 3],
    sourceBook: "소유하는 여자 3권 L693-L704; 정복하는 남자 4권 L459-L486",
    sourceExcerpt: "신체적·감각적 끌림은 관계 시작의 강한 신호일 수 있지만 장기 적합의 전부는 아니다.",
    triggerPattern: "외적 끌림만으로 적합성을 확정하거나, 반대로 끌림 없는 안정만으로 관계를 밀어붙임",
    riskExpression: "초반 몰입 뒤 운영 실패 또는 좋은 사람인데도 욕망이 없어 관계 지속 실패",
    adviceDirection: "끌림을 부정하지 않되 신뢰·존중·생활 리듬과 함께 보게 한다.",
    actionExample: "외적 끌림이 강한 상대일수록 3회 만남 동안 대화 후 피로감과 존중감을 따로 체크한다.",
    forbiddenFrame: "“외모/몸매가 전부”, “끌림은 중요하지 않다”",
    notes: "Obit 성적 끌림 섹션과 충돌하지 않게 후처리 판별용으로만 사용.",
    matchTags: ["public_contempt", "conflict_expression", "encounter_action", "charm_operation"],
    priority: 28
  },
  {
    ruleId: "C-JD-009",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2],
    sourceBook: "소유하는 여자 2권 L224-L251; 정복하는 남자 1권 L1364-L1369",
    sourceExcerpt: "강한 끌림은 내가 갖지 못했거나 억압한 면을 상대에게서 보는 투사일 수 있다.",
    triggerPattern: "늘 비슷하게 멀고, 차갑고, unavailable한 유형에게 끌림",
    riskExpression: "상대가 아니라 내 결핍을 쫓으며 반복 패턴이 고착됨",
    adviceDirection: "끌림의 대상보다 그 사람이 상징하는 욕구를 해석하게 한다.",
    actionExample: "끌리는 사람의 특성을 `내가 갖고 싶은 태도`, `실제 관계 안정성`으로 나눈다.",
    forbiddenFrame: "“강하게 끌리면 운명”, “나를 흔드는 사람이 맞는 사람”",
    notes: "자미두수 해석은 하지 않고, 이미 나온 기질 해석을 행동언어로 바꿈.",
    matchTags: ["words_over_actions", "charm_operation"],
    priority: 29
  },
  {
    ruleId: "C-JD-010",
    axisMain: true,
    axisName: "끌림-적합 판별",
    obitSections: [2, 6],
    sourceBook: "정복하는 남자 4권 L80-L87; 소유하는 여자 4권 L1127-L1137",
    sourceExcerpt: "행복한 관계는 끌림 이후의 유지 지식, 서로의 기대 차이, 관계 운영 방식을 필요로 한다.",
    triggerPattern: "좋아하는 감정만 있으면 자연스럽게 유지될 거라 믿음",
    riskExpression: "초반 이후 실망, 관계 운영 미숙, 기대 충돌",
    adviceDirection: "좋아함과 운영 가능성을 분리해서 설명한다.",
    actionExample: "상대와 `연락`, `돈`, `시간`, `갈등`, `개인공간` 기준을 초반에 가볍게 확인한다.",
    forbiddenFrame: "“좋아하면 다 맞는다”, “운명이라면 노력 없어도 유지된다”",
    notes: "섹션 2 결론과 섹션 6 준비 행동에 모두 사용.",
    matchTags: ["confirmation_seeking", "pace_control", "boundary_failure", "contact_anxiety"],
    priority: 30
  },
  {
    ruleId: "C-EP-001",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [6],
    sourceBook: "소유하는 여자 1권 L705-L720; 정복하는 남자 1권 L1285-L1303",
    sourceExcerpt: "연애에 정답은 없지만 오답은 있다. 초보일수록 득점보다 실점을 줄이는 기본기가 우선이다.",
    triggerPattern: "특별한 멘트·기술·전략을 더하려고 함",
    riskExpression: "과한 전략화, 자연스러움 상실, 치명적 실수 반복",
    adviceDirection: "새 기술보다 중단 행동을 먼저 제시한다.",
    actionExample: "이번 달 금지 행동 3개(과속 고백, 확인 추궁, 전 연인 탐색)를 정하고 체크한다.",
    forbiddenFrame: "“한 방에 먹히는 기술”, “상대를 조종하는 스킬”",
    notes: "섹션 6 최상위 실행 rule.",
    matchTags: ["confirmation_seeking", "pace_control", "words_over_actions", "conflict_expression"],
    priority: 31
  },
  {
    ruleId: "C-EP-002",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [6],
    sourceBook: "소유하는 여자 4권 L1078-L1126",
    sourceExcerpt: "갈등 대화에서는 팩트 전달과 감정 전달이 섞일 때 방어와 오해가 커진다.",
    triggerPattern: "서운함을 말할 때 사실·해석·감정을 한꺼번에 던짐",
    riskExpression: "상대는 공격으로 듣고, 본인은 공감받지 못했다고 느낌",
    adviceDirection: "위로가 필요한지 해결이 필요한지 먼저 분리하게 한다.",
    actionExample: "말하기 전 문장을 `사실`, `내 감정`, `요청` 세 줄로 다시 쓴다.",
    forbiddenFrame: "“감정적으로 말하지 마라”, “논리만 맞으면 된다”",
    notes: "실행 준비 문장으로 바로 사용 가능.",
    matchTags: ["confirmation_seeking", "pace_control", "boundary_failure", "words_over_actions"],
    priority: 32
  },
  {
    ruleId: "C-EP-003",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [6],
    sourceBook: "소유하는 여자 4권 L1054-L1077",
    sourceExcerpt: "갈등 직후에는 바로 해결보다 각자의 냉각 시간이 필요할 수 있다. 기다림 자체가 관계 행동이 될 수 있다.",
    triggerPattern: "상대가 물러나면 바로 붙잡고 설명을 요구함",
    riskExpression: "감정 회복 리듬 침범, 싸움 장기화",
    adviceDirection: "해결 의지는 남기되 회복 시간을 허용하게 한다.",
    actionExample: "“지금은 쉬고, 오늘 밤/내일 몇 시에 다시 이야기하자”처럼 시간 합의를 제안한다.",
    forbiddenFrame: "“지금 당장 풀지 않으면 끝”, “연락 안 하면 진심이 아니다”",
    notes: "C-SP-006과 연결.",
    matchTags: ["pace_control"],
    priority: 33
  },
  {
    ruleId: "C-EP-004",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [4, 6],
    sourceBook: "정복하는 남자 4권 L363-L423",
    sourceExcerpt: "접근의 첫마디는 복잡한 작업 멘트보다 자연스러운 인사가 가장 안전하다.",
    triggerPattern: "만남 기회가 있어도 멘트 준비만 하다가 실행하지 못함",
    riskExpression: "기회 상실, 자기비난, 실행 회피 강화",
    adviceDirection: "낮은 압력의 시작 행동을 제시한다.",
    actionExample: "처음에는 “안녕하세요, 자주 마주쳐서 반가워서 인사드렸어요” 수준으로 시작한다.",
    forbiddenFrame: "“작업 멘트로 경계를 무너뜨려라”, “상대를 흔드는 대사”",
    notes: "헌팅 기술이 아니라 인연 유입 행동의 최소 실행으로만 사용.",
    matchTags: ["overcentering_love", "self_routine", "approach_avoidance", "words_over_actions"],
    priority: 34
  },
  {
    ruleId: "C-EP-005",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [4, 6],
    sourceBook: "정복하는 남자 4권 L538-L546; 정복하는 남자 2권 L692-L707",
    sourceExcerpt: "관계 정의나 고백은 상호 신호가 충분할 때 명확하게 하고, 불확실한 단계에서는 행동 근거를 쌓는 편이 낫다.",
    triggerPattern: "불안해서 너무 빨리 고백하거나, 반대로 호감이 확인된 뒤에도 계속 애매하게 굼",
    riskExpression: "압박 또는 회피 인상, 타이밍 손실",
    adviceDirection: "관계 단계에 맞춰 `씨앗 행동 → 반응 관찰 → 명확한 표현` 순서로 안내한다.",
    actionExample: "상대의 선제 연락, 약속 제안, 신체/정서적 가까움 등 상호 신호 3개가 쌓인 뒤 표현한다.",
    forbiddenFrame: "“확답을 빼앗아라”, “끝까지 애매하게 굴어라”",
    notes: "타이밍 대응과도 연결.",
    matchTags: ["confirmation_seeking", "contact_anxiety", "approach_avoidance", "words_over_actions"],
    priority: 35
  },
  {
    ruleId: "C-EP-006",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [3, 6],
    sourceBook: "정복하는 남자 4권 L106-L140, L581-L590",
    sourceExcerpt: "프로필·공간·생활 이미지는 말보다 생활감과 자기관리의 단서가 된다.",
    triggerPattern: "자기소개와 말로만 매력을 설명하고 실제 생활 증거가 부족함",
    riskExpression: "신뢰와 호기심이 쌓이지 않음",
    adviceDirection: "보여주기식 과시가 아니라 생활의 정돈감과 취향을 드러내게 한다.",
    actionExample: "프로필에는 과시 사진보다 취미, 친구, 정돈된 공간, 실제 활동 사진 2~3개를 사용한다.",
    forbiddenFrame: "“외모/부 과시로 상대를 유혹”, “허세로 포장하라”",
    notes: "성별 중립의 매력 운용/실행 준비 rule.",
    matchTags: ["overcentering_love", "self_routine", "boundary_failure", "words_over_actions"],
    priority: 36
  },
  {
    ruleId: "C-EP-007",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [4, 6],
    sourceBook: "정복하는 남자 4권 L596-L618; 소유하는 여자 4권 L43-L45",
    sourceExcerpt: "상대가 가치를 두는 경험 방식을 이해하려면 실제로 그 환경을 경험해 보는 것이 도움이 된다.",
    triggerPattern: "이성이 선호하는 공간·취미·경험 소비를 이해하지 못함",
    riskExpression: "만남 제안이 자기 기준에만 머물고 접점이 좁아짐",
    adviceDirection: "상대의 세계를 평가하기 전에 경험해 보게 한다.",
    actionExample: "한 달에 한 번은 평소 가지 않던 전시, 다이닝, 클래스, 취미 모임을 직접 경험하고 대화 소재로 만든다.",
    forbiddenFrame: "“비싼 곳에 가야 가치가 생긴다”, “상대 취향을 얕봐라”",
    notes: "인연 유입 행동과 실행 준비 사이.",
    matchTags: ["overcentering_love", "self_routine", "boundary_failure", "words_over_actions"],
    priority: 37
  },
  {
    ruleId: "C-EP-008",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [6],
    sourceBook: "소유하는 여자 4권 L1237-L1241; L1293-L1295",
    sourceExcerpt: "외로움과 이별 후폭풍은 생활 습관 회복 훈련으로 다뤄야 다음 관계에 덜 끌고 간다.",
    triggerPattern: "관계 공백기에 수면·식사·음주·SNS가 무너짐",
    riskExpression: "불안정 신호 증가, 잘 맞지 않는 사람에게 쉽게 진입",
    adviceDirection: "연애 준비를 감정관리 루틴으로 구체화한다.",
    actionExample: "수면시간, 운동 20분, 음주 제한, 전 연인/SNS 탐색 차단 중 2개를 14일 체크한다.",
    forbiddenFrame: "“새 사람만 만나면 회복된다”, “외로움은 참기만 해야 한다”",
    notes: "섹션 6의 가장 직접적인 루틴 rule.",
    matchTags: ["pace_control", "overcentering_love", "self_routine", "ideal_type_confusion"],
    priority: 38
  },
  {
    ruleId: "C-EP-009",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [2, 6],
    sourceBook: "정복하는 남자 2권 L772-L805",
    sourceExcerpt: "원칙과 방향성이 없는 태도는 매력보다 불안정 인상을 만든다. 단, 고집과 원칙은 구분해야 한다.",
    triggerPattern: "상대에게 잘 보이려고 내 기준을 계속 바꿈",
    riskExpression: "자기상실, 낮은 신뢰, 장기 관계에서 누적 불만",
    adviceDirection: "상대에게 맞추기 전에 내가 유지할 기준을 먼저 언어화하게 한다.",
    actionExample: "연락, 일, 돈, 친구, 속도에서 양보 가능한 것과 불가능한 것을 각각 1개씩 정한다.",
    forbiddenFrame: "“상대 말에 전부 맞춰라”, “무조건 내 뜻대로 하라”",
    notes: "성별화된 원문을 `건강한 경계`로 변환.",
    matchTags: ["overcentering_love", "self_routine", "contact_anxiety", "confirmation_seeking"],
    priority: 39
  },
  {
    ruleId: "C-EP-010",
    axisMain: true,
    axisName: "실행 준비",
    obitSections: [6],
    sourceBook: "정복하는 남자 3권 L1460-L1497; 소유하는 여자 4권 L1096-L1126",
    sourceExcerpt: "갈등 해결에는 대화가 필요하지만, 대화는 감정 안정과 요청 구조가 있을 때 효과가 난다.",
    triggerPattern: "대화하자고 하지만 실제로는 비난·심문·판정으로 흘러감",
    riskExpression: "대화 회피, 반복 싸움, 정서적 안전감 손상",
    adviceDirection: "대화 목적을 화해, 위로, 해결, 경계 설정 중 하나로 좁히게 한다.",
    actionExample: "대화 시작 전 “오늘은 해결보다 이해를 받고 싶다”처럼 목적을 먼저 말한다.",
    forbiddenFrame: "“대화로 상대를 굴복시켜라”, “말싸움에서 이겨라”",
    notes: "C-EP-002의 확장 rule.",
    matchTags: ["approach_avoidance", "words_over_actions", "conflict_expression"],
    priority: 40
  },
  {
    ruleId: "C-SA-001",
    axisMain: false,
    axisName: "자기인식",
    obitSections: [1],
    sourceBook: "소유하는 여자 1권 L607-L703; 정복하는 남자 1권 L1216-L1233",
    sourceExcerpt: "사람은 자신이 의식한 이유보다 무의식적 끌림에 먼저 움직이고 나중에 합리화할 수 있다.",
    triggerPattern: "내가 말한 기준과 실제 선택이 반복적으로 어긋남",
    riskExpression: "자기 패턴을 모르고 같은 관계를 반복",
    adviceDirection: "말한 기준보다 실제 행동 데이터를 보게 한다.",
    actionExample: "최근 3번의 호감 선택에서 말한 이유와 실제 행동 이유를 따로 적는다.",
    forbiddenFrame: "“나는 나를 완전히 안다”, “느낌은 항상 정확하다”",
    notes: "메인 rule들의 기반 자기인식 데이터.",
    matchTags: ["overcentering_love", "self_routine", "words_over_actions"],
    priority: 41
  },
  {
    ruleId: "C-SA-002",
    axisMain: false,
    axisName: "자기인식",
    obitSections: [1],
    sourceBook: "소유하는 여자 4권 L1306-L1312",
    sourceExcerpt: "외로움은 혼자 있음 자체보다 관계 속에서 존재감이 확인되지 않을 때 커질 수 있다.",
    triggerPattern: "사람들 사이에 있어도 공허하고, 그 공허를 연애로만 해결하려 함",
    riskExpression: "관계 선택의 기준이 호감보다 확인 욕구가 됨",
    adviceDirection: "외로움의 종류를 먼저 구분하게 한다.",
    actionExample: "외로움이 올 때 `혼자라서`, `인정받지 못해서`, `말 걸 곳이 없어서` 중 무엇인지 체크한다.",
    forbiddenFrame: "“외로우면 아무 관계나 시작해라”",
    notes: "C-SP-008 보조.",
    matchTags: ["confirmation_seeking", "overcentering_love", "self_routine", "boundary_failure"],
    priority: 42
  },
  {
    ruleId: "C-MA-001",
    axisMain: false,
    axisName: "매력 운용",
    obitSections: [3, 6],
    sourceBook: "정복하는 남자 1권 L1248-L1253; 소유하는 여자 1권 L694-L703",
    sourceExcerpt: "말기술보다 반복적으로 보이는 생활 태도와 무의식적 인상이 매력에 더 큰 영향을 줄 수 있다.",
    triggerPattern: "내 매력을 구구절절 설명하려 함",
    riskExpression: "설명은 많은데 실제 감각·증거가 부족함",
    adviceDirection: "말로 설득하기보다 반복 행동으로 보이게 한다.",
    actionExample: "자기관리, 약속 시간, 대화 태도, 취미 활동 중 하나를 4주간 일관되게 노출한다.",
    forbiddenFrame: "“말빨로 설득해라”, “이미지 메이킹만 하면 된다”",
    notes: "섹션 3 매력 자산을 실행 준비로 연결.",
    matchTags: ["overcentering_love", "self_routine", "words_over_actions", "conflict_expression"],
    priority: 46
  },
  {
    ruleId: "C-MA-002",
    axisMain: false,
    axisName: "매력 운용",
    obitSections: [3],
    sourceBook: "정복하는 남자 4권 L686-L695",
    sourceExcerpt: "예상과 다른 취미·태도는 반전 매력으로 작동할 수 있다. 단, 연출이 아니라 실제 생활 자산이어야 한다.",
    triggerPattern: "내 이미지가 단조롭거나 한쪽으로만 굳어 있음",
    riskExpression: "호기심이 빨리 소진되거나 매력이 설명형으로만 남음",
    adviceDirection: "실제 취미와 생활에서 반전 포인트를 자연스럽게 드러내게 한다.",
    actionExample: "강한 이미지라면 섬세한 취미, 조용한 이미지라면 활동적 취미처럼 실제 해온 요소 1개를 프로필/대화에 배치한다.",
    forbiddenFrame: "“계산된 반전으로 상대를 흔들어라”, “없는 취미를 꾸며라”",
    notes: "Obit 성적 끌림/분위기 표현과도 연결 가능.",
    matchTags: ["conflict_expression", "charm_operation"],
    priority: 47
  },
  {
    ruleId: "C-EN-001",
    axisMain: false,
    axisName: "인연 유입 행동",
    obitSections: [4, 6],
    sourceBook: "소유하는 여자 2권 L247-L251; 정복하는 남자 4권 L404-L423",
    sourceExcerpt: "자연스러운 만남만 기다리면 실제 접점이 줄어든다. 인연은 반가운 인사와 반복 접촉에서 시작될 수 있다.",
    triggerPattern: "관계가 알아서 생기길 기다리고 내가 먼저 움직이지 않음",
    riskExpression: "기회 부족을 운 없음으로 해석",
    adviceDirection: "낮은 압력의 접촉 행동을 루틴화한다.",
    actionExample: "자주 가는 공간에서 직원/이웃/모임 사람에게 먼저 인사하고 짧은 대화를 주 2회 만든다.",
    forbiddenFrame: "“운명이라면 아무 행동 없이 온다”, “무리하게 침입하라”",
    notes: "섹션 4 보조축.",
    matchTags: ["overcentering_love", "self_routine", "boundary_failure", "words_over_actions"],
    priority: 51
  },
  {
    ruleId: "C-EN-002",
    axisMain: false,
    axisName: "인연 유입 행동",
    obitSections: [4],
    sourceBook: "정복하는 남자 4권 L529-L532; 정복하는 남자 3권 L1333-L1369",
    sourceExcerpt: "관계를 잘 이어주는 사람과 친밀한 소규모 네트워크는 새로운 접점의 현실적 통로가 된다.",
    triggerPattern: "혼자 앱/온라인만 반복하고 주변 네트워크를 쓰지 않음",
    riskExpression: "만남 풀이 좁아지고 검증된 접점이 부족함",
    adviceDirection: "소개를 좋아하는 사람, 취미 소모임, 친구의 친구 같은 검증된 경로를 활용하게 한다.",
    actionExample: "소개를 잘하는 지인 2명에게 구체적 기준 2개만 전달하고, 소모임 1곳에 4주 이상 참석한다.",
    forbiddenFrame: "“아무에게나 소개를 구걸하라”, “인맥을 이용만 하라”",
    notes: "사용자 메모의 `인연이 들어오기 쉬운 방식`과 맞물릴 때 구체 행동으로 변환.",
    matchTags: ["boundary_failure", "words_over_actions", "encounter_action"],
    priority: 52
  },
  {
    ruleId: "C-TM-001",
    axisMain: false,
    axisName: "타이밍 대응",
    obitSections: [5, 6],
    sourceBook: "정복하는 남자 4권 L547-L552",
    sourceExcerpt: "연인 이벤트가 많은 시기에는 관계 욕구가 올라갈 수 있지만, 단기 팁일 뿐 진심과 적합성을 대체하지 못한다.",
    triggerPattern: "기회기인데도 움직임이 없거나, 반대로 시즌 분위기만 믿고 무리함",
    riskExpression: "좋은 타이밍을 놓치거나, 분위기에 기대어 성급히 진입",
    adviceDirection: "타이밍은 접점 확대용으로만 쓰고 판별 기준은 별도로 유지하게 한다.",
    actionExample: "기회기에는 모임/소개/가벼운 제안을 늘리되, 관계 결정은 3회 이상 만남 뒤로 미룬다.",
    forbiddenFrame: "“시즌이면 누구든 잡아라”, “타이밍만 맞으면 성공”",
    notes: "섹션 5 올해 인연 기회의 후처리.",
    matchTags: ["encounter_action", "timing_response", "charm_operation"],
    priority: 56
  },
  {
    ruleId: "C-TM-002",
    axisMain: false,
    axisName: "타이밍 대응",
    obitSections: [5, 6],
    sourceBook: "정복하는 남자 4권 L538-L546; 정복하는 남자 2권 L692-L707",
    sourceExcerpt: "상대 신호가 없을 때는 과속 표현을 줄이고, 상호 호감이 확인된 뒤에는 애매함을 오래 끌지 않는 균형이 필요하다.",
    triggerPattern: "시기 판단을 못해 너무 빠르거나 너무 늦게 표현함",
    riskExpression: "압박 또는 기회 상실",
    adviceDirection: "호감 신호의 양에 따라 표현 강도를 조절하게 한다.",
    actionExample: "기회기에는 접촉 빈도를 늘리고, 상호 신호 3개가 생기면 명확한 제안을 한다.",
    forbiddenFrame: "“무조건 빨리 고백”, “끝까지 밀당”",
    notes: "C-EP-005의 타이밍 버전.",
    matchTags: ["conflict_expression", "timing_response"],
    priority: 57
  }
] satisfies LoveAdviceRule[];
